// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  gameId: __t.u64().primaryKey().name("game_id"),
  gameType: __t.string().name("game_type"),
  playerSpeed: __t.f32().name("player_speed"),
  winScore: __t.u32().name("win_score"),
  mapSeed: __t.u64().name("map_seed"),
  projectileBounces: __t.u32().name("projectile_bounces"),
  projectileSpeed: __t.f32().name("projectile_speed"),
  fireCooldownMs: __t.u32().name("fire_cooldown_ms"),
  damage: __t.u32(),
  gravity: __t.f32(),
  fieldHeight: __t.f32().name("field_height"),
  gapsPerPipe: __t.u32().name("gaps_per_pipe"),
  pipeGap: __t.f32().name("pipe_gap"),
  pipeSpeed: __t.f32().name("pipe_speed"),
  birdCollision: __t.bool().name("bird_collision"),
  updatedBy: __t.identity().name("updated_by"),
  updatedAt: __t.timestamp().name("updated_at"),
});
