// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  gameId: __t.u64().name("game_id"),
  name: __t.string(),
  role: __t.string(),
  speedOverride: __t.f32().name("speed_override"),
  weapon: __t.string(),
  visionRadius: __t.f32().name("vision_radius"),
  score: __t.u32(),
  alive: __t.bool(),
});
