// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const EngineConfig = __t.object("EngineConfig", {
  gameId: __t.u64(),
  config: __t.string(),
});
export type EngineConfig = __Infer<typeof EngineConfig>;

export const EngineInput = __t.object("EngineInput", {
  identity: __t.identity(),
  gameId: __t.u64(),
  input: __t.string(),
});
export type EngineInput = __Infer<typeof EngineInput>;

export const Entity = __t.object("Entity", {
  entityId: __t.u64(),
  gameId: __t.u64(),
  kind: __t.string(),
  owner: __t.option(__t.identity()),
  x: __t.f32(),
  y: __t.f32(),
  vx: __t.f32(),
  vy: __t.f32(),
  angle: __t.f32(),
  data: __t.string(),
});
export type Entity = __Infer<typeof Entity>;

export const Game = __t.object("Game", {
  gameId: __t.u64(),
  gameType: __t.string(),
  name: __t.string(),
  owner: __t.identity(),
  createdAt: __t.timestamp(),
  status: __t.string(),
});
export type Game = __Infer<typeof Game>;

export const GameRules = __t.object("GameRules", {
  gameId: __t.u64(),
  gameType: __t.string(),
  playerSpeed: __t.f32(),
  winScore: __t.u32(),
  mapSeed: __t.u64(),
  projectileBounces: __t.u32(),
  projectileSpeed: __t.f32(),
  fireCooldownMs: __t.u32(),
  damage: __t.u32(),
  gravity: __t.f32(),
  fieldHeight: __t.f32(),
  gapsPerPipe: __t.u32(),
  pipeGap: __t.f32(),
  pipeSpeed: __t.f32(),
  birdCollision: __t.bool(),
  updatedBy: __t.identity(),
  updatedAt: __t.timestamp(),
});
export type GameRules = __Infer<typeof GameRules>;

export const MapFeatures = __t.object("MapFeatures", {
  gameId: __t.u64(),
  features: __t.string(),
});
export type MapFeatures = __Infer<typeof MapFeatures>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  gameId: __t.u64(),
  name: __t.string(),
  role: __t.string(),
  speedOverride: __t.f32(),
  weapon: __t.string(),
  visionRadius: __t.f32(),
  score: __t.u32(),
  alive: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

